#%RAML 1.0 NamedExample
objects:
  -
    objecttypename: quotation
    objectproperties:
      status: active
    objectdata: abc#%RAML 1.0 NamedExample
  -
    objecttypename: ship
    objectproperties:
      status: active
    objectdata: a pretty thing
