#%RAML 1.0 DataType
type: object
properties:
  objecttypename: 
    required: true
    type: string
  objectproperties:
    required: true
    type: object
  objectdata:
    required: true
    type: any
