#%RAML 1.0
title: XSettlers Object SAPI
version: 0.5.0
description: This API implements the lowest level functions of the game engine

types:
  gameobject: !include /definitions/objectType.raml

/object:
  displayName: Game Object
  description: General class for game objects
  get:
    description: return all objects
    responses:
      200:
        body:
          application/json:
            type: gameobject[]
            
  post:
    displayName: Create New Object
    description: Add new object to the Object store, return the key assigned to the object
    body:
      application/json:
        type: gameobject
        examples: !include examples/objectExample.raml
    responses:
      201:
        body:
          application/json:
            type: string
            example: 
              ship-200514-8576

  /{ID}:
    displayName: Object by ID
    description: A game object identified by key
    get:
      description: Retrieve identified object from store
      displayName: Retrieve Object by ID
      responses:
        200:
          body:
            application/json:
              type: gameobject
              examples: !include examples/objectExample.raml
    put:
      description: Overwrite (or create) identified object in store
      displayName: Overwrite Object by ID
      body:
        application/json:
          type: gameobject
          examples: !include examples/objectExample.raml
      responses:
        200:
          body:
            application/json:
              type: gameobject
              examples: !include /examples/objectExample.raml
    delete:
        description: Remove identified object from store
        displayName: Remove Object by ID
        responses:
          200:
            body:
              application/json:
                example:
                  deleted_object_key : deleted_object_disposition

/key:
  displayName: Object Key
  description: A properly formed key associated with an object
  get:
    displayName: Make New Key
    description: Generate a new key
    queryParameters:
      key-type:
        description: One valid member of the consumer's assigned _objectset_
        required: true
        type: string
    responses:
      200:
        body:
          application/json:
            example:
              validKey : newKey
